version: '3.4'

services:
  localstack:
    image: localstack/localstack:0.11.0
    environment:
      - SERVICES=lambda
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    volumes:
      - './localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'